using CoDLuaDecompiler.Decompiler.IR.Functions;

namespace CoDLuaDecompiler.Decompiler.Analyzers.Havok
{
    /// <summary>
    /// Put the labels generated by jumps inside the instructions list instead of just a list on the function object
    /// </summary>
    public class LabelApplyAnalyzer : IAnalyzer
    {
        public void Analyze(Function f)
        {
            foreach (var l in f.Labels)
            {
                for (int i = 0; i < f.Instructions.Count; i++)
                {
                    if (f.Instructions[i].OpLocation == l.Key)
                    {
                        f.Instructions.Insert(i, l.Value);
                        break;
                    }
                }
            }
        }
    }
}