using System.Collections.Generic;

namespace CoDLuaDecompiler.Decompiler.LuaFile.Structures.LuaOpCodeTable.LuaJit
{
    public class LuaJitOpCodeTableBOCW : LuaJitOpCodeTable
    {
        protected override Dictionary<int, LuaJitOpCodeDef> ParseLuaOpCodes()
        {
            return new Dictionary<int, LuaJitOpCodeDef>
            {
                {0, LuaJitOpCode.ISLT},
                {1, LuaJitOpCode.ISGE},
                {2, LuaJitOpCode.ISLE},
                {3, LuaJitOpCode.ISGT},
                {4, LuaJitOpCode.ISEQV},
                {5, LuaJitOpCode.ISNEV},
                {6, LuaJitOpCode.ISEQS},
                {7, LuaJitOpCode.ISNES},
                {8, LuaJitOpCode.ISEQN},
                {9, LuaJitOpCode.ISNEN},
                {10, LuaJitOpCode.ISEQP},
                {11, LuaJitOpCode.ISNEP},
                {12, LuaJitOpCode.ISTC},
                {13, LuaJitOpCode.ISFC},
                {14, LuaJitOpCode.IST},
                {15, LuaJitOpCode.ISF},
                {16, LuaJitOpCode.ISTYPE},
                {17, LuaJitOpCode.ISNUM},
                {18, LuaJitOpCode.MOV},
                {19, LuaJitOpCode.NOT},
                {20, LuaJitOpCode.UNM},
                {21, LuaJitOpCode.LEN},
                {22, LuaJitOpCode.ADDVN},
                {23, LuaJitOpCode.SUBVN},
                {24, LuaJitOpCode.MULVN},
                {25, LuaJitOpCode.DIVVN},
                {26, LuaJitOpCode.MODVN},
                {27, LuaJitOpCode.ADDNV},
                {28, LuaJitOpCode.SUBNV},
                {29, LuaJitOpCode.MULNV},
                {30, LuaJitOpCode.DIVNV},
                {31, LuaJitOpCode.MODNV},
                {32, LuaJitOpCode.ADDVV},
                {33, LuaJitOpCode.SUBVV},
                {34, LuaJitOpCode.MULVV},
                {35, LuaJitOpCode.DIVVV},
                {36, LuaJitOpCode.MODVV},
                {37, LuaJitOpCode.POW},
                {38, LuaJitOpCode.CAT},
                {39, LuaJitOpCode.KSTR},
                {40, LuaJitOpCode.KHASH},
                {41, LuaJitOpCode.KCDATA},
                {42, LuaJitOpCode.KSHORT},
                {43, LuaJitOpCode.KNUM},
                {44, LuaJitOpCode.KPRI},
                {45, LuaJitOpCode.KNIL},
                {46, LuaJitOpCode.UGET},
                {47, LuaJitOpCode.USETV},
                {48, LuaJitOpCode.USETS},
                {49, LuaJitOpCode.USETN},
                {50, LuaJitOpCode.USETP},
                {51, LuaJitOpCode.UCLO},
                {52, LuaJitOpCode.FNEW},
                {53, LuaJitOpCode.TNEW},
                {54, LuaJitOpCode.TDUP},
                {55, LuaJitOpCode.GGET},
                {56, LuaJitOpCode.GSET},
                {57, LuaJitOpCode.TGETV},
                {58, LuaJitOpCode.TGETS},
                {59, LuaJitOpCode.TGETB},
                {60, LuaJitOpCode.TGETR},
                {61, LuaJitOpCode.TSETV},
                {62, LuaJitOpCode.TSETS},
                {63, LuaJitOpCode.TSETB},
                {64, LuaJitOpCode.TSETM},
                {65, LuaJitOpCode.TSETR},
                {66, LuaJitOpCode.CALLM},
                {67, LuaJitOpCode.CALL},
                {68, LuaJitOpCode.CALLMT},
                {69, LuaJitOpCode.CALLT},
                {70, LuaJitOpCode.ITERC},
                {71, LuaJitOpCode.ITERN},
                {72, LuaJitOpCode.VARG},
                {73, LuaJitOpCode.ISNEXT},
                {74, LuaJitOpCode.RETM},
                {75, LuaJitOpCode.RET},
                {76, LuaJitOpCode.RET0},
                {77, LuaJitOpCode.RET1},
                {78, LuaJitOpCode.FORI},
                {79, LuaJitOpCode.JFORI},
                {80, LuaJitOpCode.FORL},
                {81, LuaJitOpCode.IFORL},
                {82, LuaJitOpCode.JFORL},
                {83, LuaJitOpCode.ITERL},
                {84, LuaJitOpCode.IITERL},
                {85, LuaJitOpCode.JITERL},
                {86, LuaJitOpCode.LOOP},
                {87, LuaJitOpCode.ILOOP},
                {88, LuaJitOpCode.JLOOP},
                {89, LuaJitOpCode.JMP},
                {90, LuaJitOpCode.FUNCF},
                {91, LuaJitOpCode.IFUNCF},
                {92, LuaJitOpCode.JFUNCF},
                {93, LuaJitOpCode.FUNCV},
                {94, LuaJitOpCode.IFUNCV},
                {95, LuaJitOpCode.JFUNCV},
                {96, LuaJitOpCode.FUNCC},
                {97, LuaJitOpCode.FUNCCW},
                {98, LuaJitOpCode.UNKNW}
            };
        }
    }
}